spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        base-channel: base-channel
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: hashtag-group
        auto-offset-reset: earliest
      producer:
        acks: "1"
      topics:
        hashtag-adding:
          name: "hashtag-adding-topic"
          partitions: 3
          replicas: 1
        hashtag-removing:
          name: "hashtag-removing-topic"
          partitions: 3
          replicas: 1
        hashtag-analytics:
          name: "hashtag-analytics"
          partitions: 3
          replicas: 1
        hashtag-notification:
          name: "hashtag-notification"
          partitions: 3
          replicas: 1
        hashtag-achievement:
          name: "hashtag-achievement"
          partitions: 3
          replicas: 1

  elasticsearch:
    host: localhost
    port: 9200
    protocol: http

  profiles:
    active: local

server:
  port: 8090

logging:
  level:
    root: debug

user-service:
  host: localhost
  port: 8080

post-service:
  host: localhost
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /v3/api-docs

thread-pool:
  cache-calculator-pool:
    size: 1
    shutdown-timeout-seconds: 30
  cleaner-hashtag-pool:
    size: 2
    shutdown-timeout-seconds: 30

cron:
  hashtag-cache-recalculate: 0 */15 * * * *
  unused-hashtag-clean: 0 0 0 * * *

cleaner-config:
  days: 7

cache-config:
  top-hashtags-limit: 5000
  duration: 30
